spring:
  application:
    name: connecthub-user-service
server:
  port: 8082
logging:
  level:
    root: INFO
    com.connecthub.user: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
